AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket with a parameterized name in the Jakarta region.

Parameters:
  BucketName:
    Description: The name of the S3 bucket to be created.
    Type: String
    ConstraintDescription: Must be a valid S3 bucket name.

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName

Outputs:
  BucketName:
    Description: The name of the created S3 bucket.
    Value: !Ref S3Bucket